### ISSUE TITLE
Long & Short Press problem

### ISSUE THREAD

**Issue by oscdeveloper** [mprograms/SimpleRotary#2]
Hi.

I have a problem with recognizing long and short button press.

Sometimes it recognized correctly as short, but sometimes the same short became long press :/
Why? :)

During these issues encoder rotating works perfectly good all the time.

**Comment by oscdeveloper** [comment]
I found what happened :)
I put `rotary.setTrigger(LOW);` in `setup() `
It causes a problem.

**Comment by mprograms** [comment]
Sound almost like you have a floating pin. Can you post code / schematic?

**Comment by mprograms** [comment]
Not heard back. Closing.
