### ISSUE TITLE
Issues due to Serial or LCD Solution?

### ISSUE THREAD

**Issue by khawajamechatronics** [mprograms/SimpleRotary#3]
Hi,

Although library provide all the needed functions but results are not reliable. What I wish is accurate results. Even it misses some rotations thats not issue but it should register CW and CCW correct despite of using Serial or LCD.

What are possible solution for getting accurate or reliable result (CW means CW and CCW means CCW)
1- Should I add Debounce?
2- What options should I use?

Thank you for your work!

**Comment by mprograms** [comment]
Please see "Troubleshooting" under the README file. This section already addresses this issue.
