### ISSUE TITLE
Issue using encoder button

### ISSUE THREAD

**Issue by mrfunk81** [mprograms/SimpleRotary#5]
Hi and thanks for your Library, it's simple and cool.
I've an Issue using the button of the encoder, it has a negative logic, pressing it shorts his pin with GND.
I'm using setTrigger to HIGH to enable pull UP resistor and it works.. but not ever
Not all clicks are recognized, about 40% are lost and it not depends on the hardware..
Any ideas?

Thanks, Marco

**Comment by mprograms** [comment]
Can you post your code / schematic?

**Comment by mrfunk81** [comment]
Hi, this is the MENU Function

`void menu() {
init:
  pos = -1;
  int rot = 1;
  int pt = 0;

  switch (pos) {
    case 0:
      lcd.clear();
      lcd.setCursor(0, 0);
      lcd.print("    ----MENU----");
      lcd.setCursor(0, 1);
      lcd.print("SET1          <-");
      lcd.setCursor(0, 2);
      lcd.print("SET2            ");
      lcd.setCursor(0, 3);
      lcd.print("SALVA           ");
      break;
    case 1:
      lcd.clear();
      lcd.setCursor(0, 0);
      lcd.print("    ----MENU----");
      lcd.setCursor(0, 1);
      lcd.print("SET1            ");
      lcd.setCursor(0, 2);
      lcd.print("SET2          <-");
      lcd.setCursor(0, 3);
      lcd.print("SALVA           ");
      break;
    case 2:
      lcd.clear();
      lcd.setCursor(0, 0);
      lcd.print("    ----MENU----");
      lcd.setCursor(0, 1);
      lcd.print("SET1            ");
      lcd.setCursor(0, 2);
      lcd.print("SET2            ");
      lcd.setCursor(0, 3);
      lcd.print("SALVA         <-");
      break;
  }

  do {

    if (rot == 1) {
      pos = ((pos + 1) % 3);
      switch (pos) {
        case 0:
          lcd.clear();
          lcd.setCursor(0, 0);
          lcd.print("    ----MENU----");
          lcd.setCursor(0, 1);
          lcd.print("SET1          <-");
          lcd.setCursor(0, 2);
          lcd.print("SET2            ");
          lcd.setCursor(0, 3);
          lcd.print("SALVA           ");
          break;
        case 1:
          lcd.clear();
          lcd.setCursor(0, 0);
          lcd.print("    ----MENU----");
          lcd.setCursor(0, 1);
          lcd.print("SET1            ");
          lcd.setCursor(0, 2);
          lcd.print("SET2          <-");
          lcd.setCursor(0, 3);
          lcd.print("SALVA           ");
          break;
        case 2:
          lcd.clear();
          lcd.setCursor(0, 0);
          lcd.print("    ----MENU----");
          lcd.setCursor(0, 1);
          lcd.print("SET1            ");
          lcd.setCursor(0, 2);
          lcd.print("SET2            ");
          lcd.setCursor(0, 3);
          lcd.print("SALVA         <-");
          break;
      }
    }

    if (rot == 2) {
      pos = ((pos + 2) % 3);
      switch (pos) {
        case 0:
          lcd.clear();
          lcd.setCursor(0, 0);
          lcd.print("    ----MENU----");
          lcd.setCursor(0, 1);
          lcd.print("SET1          <-");
          lcd.setCursor(0, 2);
          lcd.print("SET2            ");
          lcd.setCursor(0, 3);
          lcd.print("SALVA           ");
          break;
        case 1:
          lcd.clear();
          lcd.setCursor(0, 0);
          lcd.print("    ----MENU----");
          lcd.setCursor(0, 1);
          lcd.print("SET1            ");
          lcd.setCursor(0, 2);
          lcd.print("SET2          <-");
          lcd.setCursor(0, 3);
          lcd.print("SALVA           ");
          break;
        case 2:
          lcd.clear();
          lcd.setCursor(0, 0);
          lcd.print("    ----MENU----");
          lcd.setCursor(0, 1);
          lcd.print("SET1            ");
          lcd.setCursor(0, 2);
          lcd.print("SET2            ");
          lcd.setCursor(0, 3);
          lcd.print("SALVA         <-");
          break;
      }
    }
    pt = rotary.pushType(1000);
    if (pt == 1) {
      //pt = 0;
      switch (pos) {
        case 0:
          lcd.clear();
          lcd.print(set1);
          do {
            rot = rotary.rotate();
            if (rot == 1) {
              set1 = set1 + 0.5;
              lcd.clear();
              lcd.print(set1);
            }
            if (rot == 2) {
              set1 = set1 - 0.5;
              lcd.clear();
              lcd.print(set1);
            }
            pt = rotary.pushType(1000);
            set1_cloud = set1;
          } while (pt != 1);

          set1m.write(set1);
          goto init;
          break;

        case 1:
          lcd.clear();
          lcd.print(set2);
          do {
            rot = rotary.rotate();
            if (rot == 1) {
              set2 = set2 + 0.5;
              lcd.clear();
              lcd.print(set2);
            }
            if (rot == 2) {
              set2 = set2 + 0.5;
              lcd.clear();
              lcd.print(set2);
            }
            pt = rotary.pushType(1000);
            set2_cloud = set2;
          } while (pt != 1);
          set2m.write(set2);
          goto init;
          break;

      }
    }
    pt = rotary.pushType(1000);
    rot = rotary.rotate();
  } while (!((pt == 1) && (pos == 2)));
}`
