### ISSUE TITLE
Reads every other encoder step. 

### ISSUE THREAD

**Issue by nm2kid** [mprograms/SimpleRotary#7]
This is working great for me apart from the issue that it reads every two steps instead of each individual step. Is there a way to address this problem? Thanks

**Comment by EvgeniyMakhmudov** [comment]
I think yes. In general, as i know, there are two kinds of types encoders. With single impulse counting, and double. 
Perhaps you can find mention here https://playground.arduino.cc/Main/RotaryEncoders/#Example16
Some others libraries solve this problem, for example
https://github.com/MajicDesigns/MD_REncoder/blob/master/src/MD_REncoder.h#L150
https://github.com/M-Reimer/EncoderStepCounter/blob/master/examples/BasicExample/BasicExample.ino#L6-L9

**Comment by mprograms** [comment]
As @EvgeniyMakhmudov mentioned, there are different types of rotary encoders. You may have one that is not compatible with this library.
