### ISSUE TITLE
pushType error: no matching function for call to 'Simple Rotary::pushType()'

### ISSUE THREAD

**Issue by arm358** [mprograms/SimpleRotary#8]
Working on a menu where I want a single click and also a long press -- so I believe I have to use the pushType() function.

However, it gives the error "no matching function for call to 'Simple Rotary::pushType()'" I just installed the latest version so not sure what the issue is. The example in the ReadMe pushType doesn't work either (gives same error code).

```
#include <SimpleRotary.h>

// Pin A, Pin B, Button Pin
SimpleRotary r1(6, 5, 7);


void setup() {
}

void loop() {
  int button1 = r1.pushType();


  if (button1 == 1) {
    Serial.print("button pressed.")
  }
  if (button1 == 2) {
    Serial.print("button held.")
  }
}
```

**Comment by paul-key** [comment]
I had the same problem just added time of the long push to the function call:

`r1.pushType(1000);`

**Comment by mprograms** [comment]
@paul-key  is correct. The function pushType() requires a parameter of time in milliseconds to be set. This was not clear in the documentation and will be fixed in the next release.
